# Generated by Django 3.2.14 on 2022-12-17 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CrimeModel',
        ),
    ]
