# Generated by Django 3.2.14 on 2022-12-16 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CrimeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('crime_type', models.TextField()),
                ('License', models.TextField(blank=True, max_length=8)),
                ('occupation', models.TextField(blank=True)),
                ('stage', models.TextField()),
                ('telephone', models.TextField()),
                ('datetime', models.DateTimeField()),
                ('custody', models.TextField()),
            ],
        ),
    ]
