# Generated by Django 3.2.14 on 2022-12-17 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('morvin', '0003_alter_crimemodel_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crimemodel',
            name='custody',
            field=models.TextField(choices=[('Jinja Rd Police', 'Rubaga Div Police'), ('Kiira Rd Police', 'Wandegeya div Police')], max_length=200, null=True),
        ),
    ]
