# Generated by Django 3.2.14 on 2022-12-17 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('morvin', '0004_alter_crimemodel_custody'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crimemodel',
            name='custody',
            field=models.TextField(choices=[('Jinja Rd Police', 'Jinja Rd Police'), ('Rubaga Div Police', 'Rubaga Div Police'), ('Kiira Rd Police', 'Kiira Rd Police'), ('Wandegeya div Police', 'Wandegeya div Police')], max_length=200, null=True),
        ),
    ]
