# Generated by Django 3.2.14 on 2022-12-17 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('morvin', '0005_alter_crimemodel_custody'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crimemodel',
            name='telephone',
            field=models.TextField(max_length=10),
        ),
    ]
