# Generated by Django 3.2.14 on 2022-12-19 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('morvin', '0006_alter_crimemodel_telephone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='crimemodel',
            options={},
        ),
        migrations.RemoveField(
            model_name='crimemodel',
            name='datetime',
        ),
    ]
