# Generated by Django 3.2.14 on 2022-12-19 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('morvin', '0008_auto_20221219_0916'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crimemodel',
            name='datetime',
        ),
    ]
