# Generated by Django 3.2.14 on 2022-12-19 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('morvin', '0010_auto_20221219_0950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crimemodel',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
