# Generated by Django 3.2.14 on 2022-12-23 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('morvin', '0011_alter_crimemodel_datetime'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='crimemodel',
            options={'ordering': ['pk']},
        ),
        migrations.AlterField(
            model_name='crimemodel',
            name='custody',
            field=models.CharField(choices=[('Jinja Rd Police', 'Jinja Rd Police'), ('Rubaga Div Police', 'Rubaga Div Police'), ('Kiira Rd Police', 'Kiira Rd Police'), ('Wandegeya div Police', 'Wandegeya div Police')], default='Kiira Rd Police', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='crimemodel',
            name='license',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AlterField(
            model_name='crimemodel',
            name='telephone',
            field=models.CharField(max_length=10),
        ),
    ]
